  const datos = [
        {
          nombre: "Santa Clara",
          tripulacion: 60,
          peso: 250,
          nacion: "España",
          canones: 12,
          anio_construccion: 1530,
          tipo: "carabela",
          imagen: "barco1.jpg",
        },
        {
          nombre: "La Belle Louise",
          tripulacion: 85,
          peso: 310,
          nacion: "Francia",
          canones: 16,
          anio_construccion: 1542,
          tipo: "nao",
          imagen: "barco2.jpg",
        },
        {
          nombre: "HMS Falcon",
          tripulacion: 120,
          peso: 420,
          nacion: "Inglaterra",
          canones: 22,
          anio_construccion: 1570,
          tipo: "galeón",
          imagen: "barco3.jpg",
        },
        {
          nombre: "Dronning Margrethe",
          tripulacion: 95,
          peso: 360,
          nacion: "Dinamarca",
          canones: 18,
          anio_construccion: 1558,
          tipo: "nao",
          imagen: "barco4.jpg",
        },
        {
          nombre: "San Pedro",
          tripulacion: 150,
          peso: 500,
          nacion: "España",
          canones: 28,
          anio_construccion: 1581,
          tipo: "galeón",
          imagen: "barco5.jpg",
        },
        {
          nombre: "Le Triomphe",
          tripulacion: 140,
          peso: 470,
          nacion: "Francia",
          canones: 26,
          anio_construccion: 1588,
          tipo: "galeón",
          imagen: "barco6.jpg",
        },
        {
          nombre: "HMS Swallow",
          tripulacion: 90,
          peso: 310,
          nacion: "Inglaterra",
          canones: 15,
          anio_construccion: 1529,
          tipo: "nao",
          imagen: "barco7.jpg",
        },
        {
          nombre: "Frederikshavn",
          tripulacion: 130,
          peso: 440,
          nacion: "Dinamarca",
          canones: 24,
          anio_construccion: 1576,
          tipo: "galeón",
          imagen: "barco8.jpg",
        },
        {
          nombre: "Nuestra Señora de la Paz",
          tripulacion: 180,
          peso: 560,
          nacion: "España",
          canones: 30,
          anio_construccion: 1592,
          tipo: "galeón",
          imagen: "barco9.jpg",
        },
        {
          nombre: "La Montagne",
          tripulacion: 75,
          peso: 280,
          nacion: "Francia",
          canones: 12,
          anio_construccion: 1537,
          tipo: "carabela",
          imagen: "barco10.jpg",
        },
        {
          nombre: "HMS Dragon",
          tripulacion: 160,
          peso: 490,
          nacion: "Inglaterra",
          canones: 32,
          anio_construccion: 1585,
          tipo: "galeón",
          imagen: "barco11.jpg",
        },
        {
          nombre: "Kristianstad",
          tripulacion: 110,
          peso: 400,
          nacion: "Dinamarca",
          canones: 20,
          anio_construccion: 1569,
          tipo: "nao",
          imagen: "barco12.jpg",
        },
        {
          nombre: "San Juan Bautista",
          tripulacion: 200,
          peso: 600,
          nacion: "España",
          canones: 36,
          anio_construccion: 1597,
          tipo: "galeón",
          imagen: "barco13.jpg",
        },
        {
          nombre: "Le Griffon",
          tripulacion: 70,
          peso: 260,
          nacion: "Francia",
          canones: 10,
          anio_construccion: 1515,
          tipo: "carabela",
          imagen: "barco14.jpg",
        },
        {
          nombre: "HMS Hope",
          tripulacion: 100,
          peso: 350,
          nacion: "Inglaterra",
          canones: 18,
          anio_construccion: 1548,
          tipo: "nao",
          imagen: "barco15.jpg",
        },
        {
          nombre: "Roskilde",
          tripulacion: 90,
          peso: 330,
          nacion: "Dinamarca",
          canones: 16,
          anio_construccion: 1534,
          tipo: "nao",
          imagen: "barco16.jpg",
        },
        {
          nombre: "Nuestra Señora del Mar",
          tripulacion: 240,
          peso: 650,
          nacion: "España",
          canones: 42,
          anio_construccion: 1599,
          tipo: "galeón",
          imagen: "barco17.jpg",
        },
        {
          nombre: "Le Vengeur",
          tripulacion: 135,
          peso: 460,
          nacion: "Francia",
          canones: 27,
          anio_construccion: 1580,
          tipo: "galeón",
          imagen: "barco18.jpg",
        },
        {
          nombre: "HMS Elizabeth",
          tripulacion: 210,
          peso: 610,
          nacion: "Inglaterra",
          canones: 38,
          anio_construccion: 1595,
          tipo: "galeón",
          imagen: "barco19.jpg",
        },
        {
          nombre: "Nordlys",
          tripulacion: 105,
          peso: 390,
          nacion: "Dinamarca",
          canones: 19,
          anio_construccion: 1573,
          tipo: "nao",
          imagen: "barco20.jpg",
        },
        {
          nombre: "San Bartolomé",
          tripulacion: 170,
          peso: 530,
          nacion: "España",
          canones: 29,
          anio_construccion: 1586,
          tipo: "galeón",
          imagen: "barco21.jpg",
        },
        {
          nombre: "Le Saint Michel",
          tripulacion: 125,
          peso: 450,
          nacion: "Francia",
          canones: 23,
          anio_construccion: 1579,
          tipo: "galeón",
          imagen: "barco22.jpg",
        },
        {
          nombre: "HMS Lionheart",
          tripulacion: 190,
          peso: 580,
          nacion: "Inglaterra",
          canones: 34,
          anio_construccion: 1593,
          tipo: "galeón",
          imagen: "barco23.jpg",
        },
        {
          nombre: "Freja",
          tripulacion: 115,
          peso: 410,
          nacion: "Dinamarca",
          canones: 21,
          anio_construccion: 1560,
          tipo: "nao",
          imagen: "barco24.jpg",
        },
        {
          nombre: "Santiago de Galicia",
          tripulacion: 250,
          peso: 680,
          nacion: "España",
          canones: 45,
          anio_construccion: 1598,
          tipo: "galeón",
          imagen: "barco25.jpg",
        },
      ];
